version: '3.1'

services:

  bot:
    build: .
    restart: always
#    ports:
#      - '${WEBHOOK_PORT}:${WEBHOOK_PORT:-8000}'
    entrypoint:
      - ./bin/entrypoint.sh
    depends_on:
      - postgres
      - redis
    environment:
      ADMINS: ${ADMINS}
      BOT_TOKEN: ${BOT_TOKEN}
      RATE_LIMIT: ${RATE_LIMIT:-0.5}

      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432

      DATABASE_NAME: postgres

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 5

      WEBHOOK_PORT: ${WEBHOOK_PORT}
      WEBHOOK_HOST: ${WEBHOOK_HOST:-localhost}
      WEBHOOK_PATH: ${WEBHOOK_PATH}

  redis:
    image: redis:alpine
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:
